# Site settings
title: sandbox
# email: your-email@domain.com
description: This site is a personal log.
baseurl: "https://t-mochizuki.github.io/sandbox"
url: ""

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
